# Generated by Django 2.0.7 on 2019-09-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190930_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sumary',
            field=models.TextField(),
        ),
    ]
