# Generated by Django 2.0.7 on 2019-09-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sumary',
            field=models.TextField(blank=True),
        ),
    ]
